name: cloud_hook
description: "Cloud Hooks"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.0.2
  googleapis_auth: ^1.6.0
  html: ^0.15.4
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.0.15
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.6
  json_annotation: ^4.9.0
  logger: ^2.2.0
  readmore: ^3.0.0
  media_kit: ^1.1.10                             
  media_kit_video: ^1.2.4                        
  media_kit_libs_video: ^1.0.4 
  fast_cached_network_image: ^1.2.9
  collection: ^1.18.0
  material_symbols_icons: ^4.2741.0
  flutter_localizations:
    sdk: flutter
  intl: any
  firebase_dart: ^1.1.4
  dio: ^5.4.3+1
  http: ^1.2.1
  equatable: ^2.0.5
  scrollable_positioned_list: ^0.3.8
  google_sign_in: ^6.2.1
  riverpod_annotation: ^2.3.5
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.5.1
  device_info_plus: ^10.1.0
  simple_rc4: ^0.3.0

dependency_overrides:
  analyzer:
  media_kit: 
    git:
      url: https://github.com/media-kit/media-kit
      path: media_kit
      ref: 13f6b3
  media_kit_video: 
    git:
      url: https://github.com/media-kit/media-kit
      path: media_kit_video
      ref: 13f6b3
  media_kit_libs_video: 
    git:
      url: https://github.com/media-kit/media-kit
      path: libs/universal/media_kit_libs_video
      ref: 13f6b3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  isar_generator: ^3.1.0+1
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - secrets.json
