name: cloud_hook
description: "Cloud Hooks"
publish_to: 'none'
version: 1.1.1

isar_version: 3.1.7
media_kit_version: 50c510d

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: "3.22.3"

dependencies:
  flutter:
    sdk: flutter
  intl: 
  flutter_localizations:
    sdk: flutter
  #routing
  go_router: ^14.2.0
  # auth + firebase
  googleapis_auth: ^1.6.0
  google_sign_in: ^6.2.1
  firebase_dart: ^1.1.4
  #parsing
  html: ^0.15.4
  dio: ^5.4.3+1
  http: ^1.2.2
  # storage
  path_provider: ^2.0.15
  # isar: ^3.1.0+1
  # isar_flutter_libs: ^3.1.0+1
  isar: 
    version: &isar_version
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs: # contains Isar Core
    version: &isar_version
    hosted: https://pub.isar-community.dev/
  shared_preferences: ^2.2.2
  # media kit
  media_kit:                              
  media_kit_video:                         
  media_kit_libs_video:  
  # itility widgets
  scrollable_positioned_list: ^0.3.8
  readmore: ^3.0.0
  material_symbols_icons: ^4.2771.0
  # state managment
  riverpod_annotation: ^2.3.5
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.5.1
  # encryption
  simple_rc4: ^0.3.0
  pointycastle: ^3.9.1
  encrypt: ^5.0.3
  js_unpack: ^1.0.4
  # utillity
  logger: ^2.2.0
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  url_launcher: ^6.3.0
  collection: ^1.18.0
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  window_manager: ^0.3.9
  fast_cached_network_image: ^1.2.9
  cached_network_image: ^3.3.1

dependency_overrides:
  media_kit: 
    git:
      url: https://github.com/media-kit/media-kit
      path: media_kit
      ref: &media_kit_version
  media_kit_video: 
    git:
      url: https://github.com/media-kit/media-kit
      path: media_kit_video
      ref: &media_kit_version
  media_kit_libs_video: 
    git:
      url: https://github.com/media-kit/media-kit
      path: libs/universal/media_kit_libs_video
      ref: &media_kit_version
  intl: 

dev_dependencies:
  analyzer: ^6.4.1
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  # isar_generator: ^3.1.0+1
  isar_generator: 
    version: &isar_version
    hosted: https://pub.isar-community.dev/
  custom_lint: ^0.6.4
  json_serializable: ^6.8.0
  test: ^1.25.2
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - secrets.json
