name: content_suppliers_rust
description: "Content Suppliers RUST bindings"
version: 0.0.1
homepage:

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.24.0"

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: 2.6.0
  plugin_platform_interface: ^2.0.2
  content_suppliers_api:
    path: ../content_suppliers_api
  freezed_annotation: ^2.4.4
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.5.7
  integration_test:
    sdk: flutter
  build_runner: ^2.4.13
  test: ^1.25.7
