name: content_suppliers_ffi
description: "Content Suppliers FFI bindings"
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.1
  flutter: '>=3.3.0'

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: 2.6.0
  plugin_platform_interface: ^2.0.2
  content_suppliers_api:
    path: ../content_suppliers_api
  ffi: ^2.1.3
  flat_buffers: ^23.5.26
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  integration_test:
    sdk: flutter
  test: ^1.25.7
