name: content_suppliers_dart
description: "Content Suppliers Dart implementaions"
version: 0.0.1
homepage:

publish_to: none

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  content_suppliers_api:
    path: ../content_suppliers_api
  #parsing
  html: ^0.15.4
  dio: ^5.6.0
  http: ^1.2.2
  # encryption
  simple_rc4: ^0.3.0
  pointycastle: ^3.9.1
  encrypt: ^5.0.3
  js_unpack: ^1.0.4
  # utillity
  logger: ^2.2.0
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  collection: ^1.18.0

  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  test: ^1.25.2

flutter:
