// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.4.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

List<String> getChannels({required String supplier}) =>
    RustLib.instance.api.crateApiBridgeGetChannels(supplier: supplier);

List<String> getDefaultChannels({required String supplier}) =>
    RustLib.instance.api.crateApiBridgeGetDefaultChannels(supplier: supplier);

List<ContentType> getSupportedTypes({required String supplier}) =>
    RustLib.instance.api.crateApiBridgeGetSupportedTypes(supplier: supplier);

List<String> getSupportedLanguages({required String supplier}) =>
    RustLib.instance.api
        .crateApiBridgeGetSupportedLanguages(supplier: supplier);

Future<List<ContentInfo>> search(
        {required String supplier,
        required String query,
        required List<String> types}) =>
    RustLib.instance.api
        .crateApiBridgeSearch(supplier: supplier, query: query, types: types);

Future<List<ContentInfo>> loadChannel(
        {required String supplier,
        required String channel,
        required int page}) =>
    RustLib.instance.api.crateApiBridgeLoadChannel(
        supplier: supplier, channel: channel, page: page);

Future<ContentDetails?> getContentDetails(
        {required String supplier, required String id}) =>
    RustLib.instance.api
        .crateApiBridgeGetContentDetails(supplier: supplier, id: id);

Future<List<ContentMediaItem>> loadMediaItems(
        {required String supplier,
        required String id,
        required List<String> params}) =>
    RustLib.instance.api.crateApiBridgeLoadMediaItems(
        supplier: supplier, id: id, params: params);

Future<List<ContentMediaItemSource>> loadMediaItemSources(
        {required String supplier,
        required String id,
        required List<String> params}) =>
    RustLib.instance.api.crateApiBridgeLoadMediaItemSources(
        supplier: supplier, id: id, params: params);

List<String> avalaibleSuppliers() =>
    RustLib.instance.api.crateApiBridgeAvalaibleSuppliers();
