name: content_suppliers_api
description: "Content Suppliers API"
version: 0.0.1
homepage:

publish_to: none

environment:
  sdk: ^3.5.1
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
