name: Release

on:
  workflow_dispatch:

jobs:
  build-for-linux:
    runs-on: ubuntu-latest
    name: "Release for Linux"
    permissions: write-all
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake libgtk-3-dev ninja-build libstdc++-12-dev liblzma-dev mpv unzip libmpv-dev
        shell: bash
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
      - name: Get Flutter dependencies
        run: flutter pub get
        shell: bash
      - name: Build Flutter for Linux
        run: flutter build linux
        shell: bash
      - name: Package linux build output
        run: tar -zcvf cloud_hook.tar.gz -C build/linux/x64/release/bundle .
        shell: bash
      - name: Upload linux outputs
        uses: actions/upload-artifact@v4
        with:
          name: linux_outputs
          path: cloud_hook.tar.gz
      