name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      android:
        description: 'Build Android'
        required: false
        type: boolean
      linux:
        description: 'Build Linux'
        required: false
        type: boolean
      windows:
        description: 'Build Windows'
        required: false
        type: boolean

jobs:
  build-for-android:
    runs-on: ubuntu-latest
    name: "Buid for Android"
    permissions: write-all
    if: startsWith(github.ref, 'refs/tags/') || inputs.android
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          fetch-tags: true
      - name: Create secrets
        run: |
          echo "$SECRETS_JSON" > secrets.json
          echo "$GOOGLE_SERVICE_JSON" > android/app/google-services.json
          echo "$ANDOID_KEYSTORE_B64" | base64 -di > android/app/cloud_hook.jks
        env:
          SECRETS_JSON: ${{ secrets.SECRETS_JSON }}
          GOOGLE_SERVICE_JSON: ${{ secrets.GOOGLE_SERVICE_JSON }}
          ANDOID_KEYSTORE_B64: ${{ secrets.ANDOID_KEYSTORE_B64 }}
      - name: Extract tag name
        run: |
          git fetch --tags
          TAG=$(git describe --abbrev=0 --tags)
          echo "TAG=$TAG-$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
        shell: bash
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          cache: true
      - name: Get Flutter dependencies
        run: flutter pub get
      - name: Build Flutter for Android
        run: flutter build apk --split-per-abi --build-name $TAG
      - name: Upload android outputs
        uses: actions/upload-artifact@v4
        with:
          name: android_outputs
          path: build/app/outputs/flutter-apk/app-*-release.apk
          retention-days: 7

  build-for-linux:
    runs-on: ubuntu-latest
    name: "Buid for Linux"
    permissions: write-all
    if: startsWith(github.ref, 'refs/tags/') || inputs.linux
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
      - name: Create secrets
        run: echo "$SECRETS_JSON" > secrets.json
        env:
          SECRETS_JSON: ${{ secrets.SECRETS_JSON }}
      - name: Extract tag name
        run: |
          git fetch --tags
          TAG=$(git describe --abbrev=0 --tags)
          echo "TAG=$TAG-$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
        shell: bash
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake libgtk-3-dev ninja-build libstdc++-12-dev liblzma-dev mpv unzip libmpv-dev
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          cache: true
      - name: Get Flutter dependencies
        run: flutter pub get
      - name: Build Flutter for Linux
        run: flutter build linux --build-name $TAG
      - name: Upload linux outputs
        uses: actions/upload-artifact@v4
        with:
          name: linux-outputs
          path: build/linux/x64/release/bundle/
          retention-days: 7

  build-for-windows:
    runs-on: windows-latest
    name: "Buid for Windows"
    permissions: write-all
    if: startsWith(github.ref, 'refs/tags/') || inputs.windows
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
      - name: Create secrets
        run: |
         echo "$SECRETS_JSON" > secrets.json
        shell: bash
        env:
          SECRETS_JSON: ${{ secrets.SECRETS_JSON }}
      - name: Extract tag name
        run: |
          git fetch --tags
          TAG=$(git describe --abbrev=0 --tags)
          echo "TAG=$TAG-$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
        shell: bash
      - run: choco install yq
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          cache: true
      - name: Get Flutter dependencies
        run: flutter pub get
      - name: Build Flutter for Windows
        run: flutter build windows --build-name $TAG
      - name: Upload windows outputs
        uses: actions/upload-artifact@v4
        with:
          name: windows-outputs
          path: build/windows/x64/runner/Release/
          retention-days: 7

  release:
    runs-on: ubuntu-latest
    name: "Release"
    permissions: write-all
    needs: [build-for-android, build-for-linux, build-for-windows]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: android_outputs
          path: android_outputs
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: linux-outputs
          path: linux-outputs
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: windows-outputs
          path: windows-outputs
      - name: RePackage Desktops
        run: |
          tar -czf linux-x64.tar.gz -C linux-outputs .
          zip -r windows-x64.zip windows-outputs
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            android_outputs/*
            linux-x64.tar.gz
            windows-x64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}