name: Release

on:
  workflow_dispatch:

jobs:
  build-for-android:
    runs-on: ubuntu-latest
    name: "Buid for Android"
    permissions: write-all
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
      - name: Create secrets
        run: |
          echo "$SECRETS_JSON" > secrets.json
          echo "$GOOGLE_SERVICE_JSON" > android/app/google-services.json
          echo "$ANDOID_KEYSTORE_B64" | base64 -di > android/app/cloud_hook.jks
        env:
          SECRETS_JSON: ${{ secrets.SECRETS_JSON }}
          GOOGLE_SERVICE_JSON: ${{ secrets.GOOGLE_SERVICE_JSON }}
          ANDOID_KEYSTORE_B64: ${{ secrets.ANDOID_KEYSTORE_B64 }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          cache: true
      - name: Get Flutter dependencies
        run: flutter pub get
      - name: Build Flutter for Android
        run: flutter build apk --split-per-abi
      - name: Upload android outputs
        uses: actions/upload-artifact@v4
        with:
          name: android_outputs
          path: build/app/outputs/flutter-apk/app-*-release.apk

  release:
  build-for-linux:
    runs-on: ubuntu-latest
    name: "Buid for Linux"
    permissions: write-all
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
      - name: Create secrets
        run: echo "$SECRETS_JSON" > secrets.json
        env:
          SECRETS_JSON: ${{ secrets.SECRETS_JSON }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake libgtk-3-dev ninja-build libstdc++-12-dev liblzma-dev mpv unzip libmpv-dev
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          cache: true
      - name: Get Flutter dependencies
        run: flutter pub get
      - name: Build Flutter for Linux
        run: flutter build linux
      - name: Upload linux outputs
        uses: actions/upload-artifact@v4
        with:
          name: linux-x64
          path: build/linux/x64/release/bundle/

  build-for-windows:
    runs-on: windows-latest
    name: "Buid for Windows"
    permissions: write-all
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
      - name: Create secrets
        run: |
         echo "$SECRETS_JSON" > secrets.json
        shell: bash
        env:
          SECRETS_JSON: ${{ secrets.SECRETS_JSON }}
      - run: choco install yq
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          cache: true
      - name: Get Flutter dependencies
        run: flutter pub get
      - name: Build Flutter for Windows
        run: flutter build windows
      - name: Upload windows outputs
        uses: actions/upload-artifact@v4
        with:
          name: windows-x64
          path: build/windows/x64/runner/Release/